### ISSUE TITLE
Needs `contact` field

### ISSUE THREAD

**Issue by Ads20000** [snapcrafters/minikube#1]
Minikube needs a `contact` field in the store. Probably should be `https://github.com/snapcrafters/minikube/issues`.

Edit: Although I can see that this repo hasn't been transferred yet lol!

**Comment by popey** [comment]
Blocked on: https://bugs.launchpad.net/snapstore/+bug/1692037

**Comment by popey** [comment]
This doesn't appear to be published by snapcrafters.
